services:
  postgres:
    image: postgres:14.6
    volumes:
      - postgres:/var/lib/postgresql/data/  
    env_file:
      - ./userAPI/.env
    expose:
      - "5432"
  userAPI:
    build:
      context: .
      dockerfile: ./userAPI/Dockerfile 
    image: userapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./userAPI:/app
    env_file:
      - ./userAPI/.env
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./userAPI/.env
    ports:
      - "3000:80"
    tty: true

volumes:
  postgres:
