version: "3"
services:
  postgres:
    image: postgres:14.6
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
  userAPI:
    build:
      context: ./userAPI
    image: userapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./userAPI:/app
    environment:
      - DB_CONN=${DB_CONN}
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "3000:80"
    tty: true

volumes:
  postgres:
